[pytest]
# Indica a pytest que añada el directorio actual al PYTHONPATH para resolver el paquete 'src'
pythonpath = .

# Configuración de descubrimiento de pruebas
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Opciones de salida predeterminadas
addopts = -v --strict-markers